Feature/config page
Azure/Verified-Telemetry-Solution-Sample pull request #8
Opened 2021-05-27 18:37 UTC by sumukhmarathe

Made configuration of connection string and device id dynamic. Created a simple form for user input. Refer to updated Readme for new steps.

2021-05-27 18:39 UTC, ryanwinter commented
Cool, let me try this out!

2021-05-27 20:44 UTC, ryanwinter requested changes
I think adding a dashboard link from grafana to the config page would be helpful here, then if people accidently miss the docs they will at least hopefully see a configure link on the dashboard.

https://grafana.com/docs/grafana/latest/linking/dashboard-links/

2021-05-27 20:44 UTC, ryanwinter commented on app/HTTPServer.js
> +            body = 'Invalid IoT Hub Connection String! <a href="http://localhost:8080/configuration-form">Reopen Solution Sample Configuration</a>'
Update this to http://localhost:8080 if the above change request makes sense.

2021-05-28 15:28 UTC, sumukhmarathe commented on README.md
> +  ![Save Config](./media/config_landing_page_save.png)
have 2 screenshots now. Let me know if you think first one is necessary

2021-05-28 15:28 UTC, sumukhmarathe commented on README.md
> +
Changed cursor type to "pointer" from "grabbing"

2021-05-28 15:28 UTC, sumukhmarathe commented on README.md
> +  ![Failure in Configuration](./media/config_landing_page_error_redirect.png)
done

2021-05-28 15:28 UTC, sumukhmarathe commented on app/HTTPServer.js
> +    app.get('/configuration-form', function (req, res)
Kept form at /configuration-form but added a redirect at root which will take user to /configuration-form

2021-06-11 13:04 UTC, sumukhmarathe commented
Hey Ryan, can you review the changes done?

2021-06-23 18:57 UTC, ryanwinter commented on app/HTTPServer.js
> +            body = 'Invalid IoT Hub Connection String! <a href="http://localhost:8080/configuration-form">Reopen Solution Sample Configuration</a>'
I think this caused a problem because the commands sent from the Grafana are sent to this top level URL.

2021-06-23 19:00 UTC, ryanwinter commented on app/HTTPServer.js
> +            body = 'Invalid IoT Hub Connection String! <a href="http://localhost:8080/configuration-form">Reopen Solution Sample Configuration</a>'
I reverted this back because it was blocking my testing.

2021-06-23 19:01 UTC, ryanwinter commented on app/HTTPServer.js
> +            body = 'Invalid IoT Hub Connection String! <a href="http://localhost:8080/configuration-form">Reopen Solution Sample Configuration</a>'
Here is where this URL is used: https://github.com/Azure/Verified-Telemetry-Solution-Sample/blob/9c62cb0f48249cfc8470a660319ff7e3e2518895/grafana/provisioning/dashboards/VerifiedTelemetryGSGDashboard.json#L206

2021-06-23 19:01 UTC, ryanwinter commented
> Hey Ryan, can you review the changes done?

Done, sorry for slow response

2021-06-23 20:00 UTC, ryanwinter approved these changes

2021-06-25 21:19 UTC, merged